name: Format Code with GoogleJavaFormat 

on:
  workflow_dispatch: # on button click
  push:
    branches:
      - '*'
    #branches:  [ "dev", "main" ]
  pull_request:
    branches:
      - '*'
    #branches: [ "dev", "main" ]
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
    
jobs:
  formattingKotlin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v2 minimum required
        with:
          submodules: 'true'
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Git Pull
        run: git pull
        
      - name: Google Java Format"
        uses: axel-op/googlejavaformat-action@v3
        with:
          files: "**/*.kt"
          args: "--skip-sorting-imports --replace"
          # Recommended if you use MacOS:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: Print diffs
#        run: git --no-pager diff --exit-code

  formattingJava:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v2 minimum required
        with:
          submodules: 'true'
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Git Pull
        run: git pull
        
      - name: Google Java Format"
        uses: axel-op/googlejavaformat-action@v3
        with:
          files: "**/*.java"
          args: "--skip-sorting-imports --replace"
          # Recommended if you use MacOS:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: Print diffs
#        run: git --no-pager diff --exit-code
  formattingGradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v2 minimum required
        with:
          submodules: 'true'
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Git Pull
        run: git pull
        
      - name: Google Java Format"
        uses: axel-op/googlejavaformat-action@v3
        with:
          files: "**/*.*.kts"
          args: "--skip-sorting-imports --replace"
          # Recommended if you use MacOS:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: Print diffs
#        run: git --no-pager diff --exit-code
